package com.example.other

object Constants {
    val MAX_ROOM_SIZE = 8
    val TYPE_CHAT_MESSAGE = "TYPE_CHAT_MESSAGE"
    val TYPE_DRAW_DATA = "TYPE_DRAW_DATA"
    val TYPE_ANNOUNCEMENT_DATA = "TYPE_ANNOUNCEMENT_DATA"
    val TYPE_JOIN_ROOM_HANDSHAKE = "TYPE_JOIN_ROOM_HANDSHAKE"
    val TYPE_GAME_ERROR = "TYPE_GAME_ERROR"
}