package com.example.other

object Constants {
    val MAX_ROOM_SIZE = 8
    val TYPE_CHAT_MESSAGE = "TYPE_CHAT_MESSAGE"
    val TYPE_DRAW_DATA = "TYPE_DRAW_DATA"
    val TYPE_ANNOUNCEMENT_DATA = "TYPE_ANNOUNCEMENT_DATA"
    val TYPE_JOIN_ROOM_HANDSHAKE = "TYPE_JOIN_ROOM_HANDSHAKE"
    val TYPE_GAME_ERROR = "TYPE_GAME_ERROR"
    val TYPE_PHASE_CHANGE = "TYPE_PHASE_CHANGE"
    val TYPE_CHOSEN_WORD = "TYPE_CHOSEN_WORD"
    val TYPE_GAME_STATE = "TYPE_GAME_STATE"
    val TYPE_NEW_WORDS = "TYPE_NEW_WORDS"
}